apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zora
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - zoratech.dev
    secretName: ingressgateway-certs
  rules:
  - host: "zoratech.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80